# import jwt.utils
import time
import math
from os import access
import requests
import json
import random
import string

def storeMaker(numStores):
    random.seed(time.time())

    restaurantNames = [
    "The Golden Fork",
    "Saffron & Sage",
    "The Rustic Table",
    "Ember & Oak",
    "Ocean's Bounty",
    "Urban Spice",
    "The Harvest Moon",
    "Blue Lantern Bistro",
    "The Secret Garden Cafe",
    "The Velvet Spoon",
    "Basil & Barrel",
    "Whisk & Willow",
    "The Salted Plum",
    "Crimson & Clover",
    "Cloud Nine Eatery",
    "The Sunflower Grill",
    "The Copper Kettle",
    "Velvet Vine",
    "Bramble & Thyme",
    "Lotus & Lime",
    "Willow & Walnut",
    "Hearth & Home",
    "The Ivy Room",
    "Ember’s Edge",
    "The Greenhouse Grill",
    "The Peach Pit",
    "Moonlit Morsels",
    "The Ivory Bean",
    "Tanglewood Tavern",
    "The Gilded Lily",
    "Cinnamon & Stone",
    "The Birch & Barrel",
    "Harborview Grill",
    "Velvet Oak",
    "The Spice Lab",
    "Emberstone Kitchen",
    "Cravings & Co.",
    "The Driftwood Diner",
    "The Maple & Mallow",
    "The Meadow Cafe",
    "The Hidden Pearl",
    "Celestial Tastes",
    "The Golden Hive",
    "Alchemist’s Table",
    "The Green Lantern",
    "The Bamboo Grove",
    "The Blue Poppy",
    "Moonstone Bistro",
    "Truffle & Thyme",
    "The Lantern Room",
    "Copper & Clay",
    "Harvest & Hearth",
    "Ember’s Edge",
    "The Wooden Spoon",
    "The Garden Gate",
    "Sea & Sage",
    "The Rustic Oyster",
    "Lime & Lavender",
    "The Blue Tonic",
    "The Roasted Chestnut",
    "The Local Herb",
    "The Urban Palate",
    "Lush & Vine",
    "Tides & Treasures",
    "The Gold Leaf",
    "Twilight Tavern",
    "Wildflower & Oak",
    "The Silver Fern",
    "Mistral Bistro",
    "The Quill & Plate",
    "Ivy & Iron",
    "The Lime & Laurel",
    "Willowbrook Diner",
    "Emberwood Tavern",
    "Salt & Sea",
    "The Blushing Rose",
    "Hearthstone Grill",
    "The Painted Table",
    "The Olive Grove",
    "The Enchanted Spoon",
    "The Maple Leaf",
    "The Saffron Spoon",
    "The Green Bean Cafe",
    "Stone & Vine",
    "The Timber & Tine",
    "The Garnet Table",
    "Wild Oak Grill",
    "The Silver Spoon",
    "Fireside Feast",
    "The Willow Way",
    "The Pine & Poplar",
    "Red Fox & Sage",
    "Harvest & Hearth",
    "Luna’s Feast",
    "The Rusted Knife",
    "Saffron & Sea Salt",
    "The Majestic Oak",
    "Olive & Ash",
    "The Magnolia House",
    "Cobalt & Clover",
    "Lavender & Leeks",
    "The Orchard Plate",
    "The Velvet Peach",
    "Horizon Bistro",
    "Greenleaf & Grains",
    "The Chestnut Tree",
    "The Copper Fox",
    "The Wild Beet",
    "Ocean Breeze Cafe",
    "The Pine Grove",
    "The Moonlit Fork",
    "Truffle & Tine",
    "Maple & Iron",
    "Vine & Dine",
    "The Lily Pond",
    "The Golden Leaf",
    "The Pecan Press",
    "Sage & Cedar",
    "The Garden Feast",
    "The Tasting Room",
    "The Blue Olive",
    "Ember & Elms",
    "Bramble & Ember",
    "The Salted Herb",
    "Solstice & Spice",
    "The Pearl Oyster",
    "Driftwood & Dune",
    "The Cedar Roost",
    "The Green Prairie",
    "The Wandering Spoon",
    "Honey & Thyme",
    "Iron & Ivy",
    "The Brass Lantern",
    "The Harvest Table",
    "The Roasted Oak",
    "Lantern & Lace",
    "Fireside Feast",
    "The Painted Pine",
    "The Ivy Oak",
    "Ruby & Roam",
    "Moonlit Harvest",
    "The Copper Oak",
    "Twilight & Tastes",
    "The Maple Grove",
    "The Glass Lantern",
    "Autumn & Sage",
    "Maple & Mustard",
    "The Birch Bistro",
    "The Rustic Maple",
    "Velvet & Vine",
    "The Sage Brush",
    "The Silver Oak",
    "Lavender & Lime",
    "The Wood & Vine",
    "Ember Grove",
    "Rustic & Rare",
    "Pine & Palate",
    "The Harvesting Table",
    "Willow’s End",
    "The Driftwood Grill",
    "Smoke & Sage",
    "The Starlight Eatery",
    "Juniper & Stone",
    "The Hearthstone Tavern",
    "The Oak & Olive",
    "Wildwood Kitchen",
    "Poppy & Pine",
    "The Fireside Grill",
    "The Golden Thyme",
    "The Sea & Sizzle",
    "Fireside & Vine",
    "The Velvet Vine",
    "The Cranberry Cottage",
    "The Peony Place",
    "The Woodland Fork",
    "Maple & Mirth",
    "The Garden Loft",
    "Harvest & Vine",
    "The Roasted Vine",
    "The Red Barn Bistro",
    "Juniper & Maple",
    "Willow’s Way",
    "The Amber Fork",
    "Ember & Earth",
    "Crimson Clover",
    "The Pine Nook",
    "The Driftwood Bistro",
    "Salt & Sage Kitchen",
    "Blossom & Basil",
    "The Bluewood Grill",
    "The Sweet Fern",
    "Citrus & Cedar",
    "The Ruby Root",
    "Cedar & Spice",
    "Sprout & Stone",
    "Timber & Torch",
    "Sage & Savory",
    "The Golden Oak",
    "The Blush Vine",
    "The Secret Table"
]

    zipCode = range(80000, 81658)
    streetNames = [
    "Oak Street",
    "Maple Avenue",
    "Pine Lane",
    "Cedar Drive",
    "Elm Road",
    "Willow Way",
    "Birch Boulevard",
    "Cherry Court",
    "Rosemary Lane",
    "Sunset Boulevard",
    "Silver Birch Way",
    "Golden Hill Drive",
    "Harrison Street",
    "Park Avenue",
    "Broadway Avenue",
    "Main Street",
    "King Street",
    "Queen Road",
    "Victoria Lane",
    "Adams Boulevard",
    "Jefferson Street",
    "Madison Avenue",
    "Franklin Road",
    "Beverly Hills Drive",
    "Crescent Street",
    "Glenwood Drive",
    "Sapphire Lane",
    "Blue Ridge Road",
    "Shady Grove Street",
    "Riverside Drive",
    "Mountain View Way",
    "Sunrise Road",
    "Whispering Pines Avenue",
    "Silver Oak Road",
    "Wellington Place",
    "Springfield Avenue",
    "Eastwood Drive",
    "Westfield Street",
    "Lakeshore Road",
    "Stonebridge Avenue",
    "Willowbrook Drive",
    "Hawthorne Lane",
    "Pecan Street",
    "Canyon Drive",
    "Cottonwood Lane",
    "Lily Pad Road",
    "Rainbow Avenue",
    "Carmichael Street",
    "Redwood Court",
    "Ashford Street",
    "Heritage Lane",
    "Timber Ridge Road",
    "Golden Eagle Way",
    "Sycamore Place",
    "Riverbend Road",
    "Cypress Street",
    "Maplewood Drive",
    "Pleasantview Road",
    "Lakeside Drive",
    "Sunshine Street",
    "Willow Glen Road",
    "Fairway Drive",
    "Riverstone Avenue",
    "Wildflower Lane",
    "Eaglecrest Boulevard",
    "Seaside Drive",
    "Horizon Street",
    "Linden Avenue",
    "Chestnut Street",
    "Morning Glory Way",
    "Country Club Drive",
    "Autumn Lane",
    "Brookstone Avenue",
    "Crescent Moon Road",
    "Old Mill Road",
    "Tanglewood Drive",
    "Rosewood Avenue",
    "Hickory Street",
    "Magnolia Drive",
    "Holly Lane",
    "Cloverfield Road",
    "Poppy Ridge Street",
    "Silverleaf Court",
    "Pinehurst Drive",
    "Gingerbread Lane",
    "Cherry Blossom Road",
    "Aspen Heights",
    "Royal Oak Drive",
    "Briarwood Street",
    "Mountain Crest Road",
    "Goldenrod Way",
    "Larchmont Avenue",
    "Northwood Avenue",
    "Southgate Drive",
    "Maple Ridge Road",
    "Summit View Drive",
    "Northstar Boulevard",
    "Oakridge Lane",
    "Ridgeview Road",
    "Treetop Lane",
    "Lakeview Street",
    "Hillside Drive",
    "Cottonwood Court",
    "Bluebell Street",
    "Crimson Drive",
    "Foxglove Avenue",
    "Evergreen Street",
    "Sagebrush Way",
    "Pinecrest Boulevard",
    "Sandstone Road",
    "Boulder Ridge Road",
    "Vista View Avenue",
    "Sunset Ridge Drive",
    "Glenview Avenue",
    "Brandywine Street",
    "Wildwood Boulevard",
    "Waterfall Road",
    "Serenity Drive",
    "Harborview Road",
    "Woodland Drive",
    "Almond Street",
    "Lilac Lane",
    "Daisy Hill Road",
    "Greenfield Street",
    "Stonehill Road",
    "Cattail Drive",
    "Autumn Ridge Drive",
    "Birchwood Lane",
    "Copper Ridge Road",
    "Springbrook Avenue",
    "Brooklyn Lane",
    "Juniper Lane",
    "Rosehill Avenue",
    "Wisteria Road",
    "Windmill Drive",
    "Sunflower Street",
    "Dawn Road",
    "Birch Glen Drive",
    "Red Cedar Drive",
    "Creekside Boulevard",
    "Aspen Park Avenue",
    "Mossy Rock Lane",
    "Sand Dune Drive",
    "Hummingbird Lane",
    "Violet Street",
    "Windy Hill Road",
    "Sierra Vista Road",
    "Granite Ridge Drive",
    "Honeybee Lane",
    "Silverwood Lane",
    "Wildflower Drive",
    "Cricket Court",
    "Pebble Beach Road",
    "Echo Ridge Drive",
    "Sable Street",
    "Marigold Avenue",
    "Skyline Drive",
    "Falcon Street",
    "Fox Run Road",
    "Lime Street",
    "Turtle Creek Drive",
    "Bison Ridge Road",
    "Blossom Hill Drive",
    "Ivy Lane",
    "Copperstone Road",
    "Thunderbird Boulevard",
    "Cliffside Drive",
    "Hidden Creek Lane",
    "Ironwood Road",
    "Wintergreen Drive",
    "Fieldstone Lane",
    "Coyote Hill Road",
    "Hickory Hollow Road",
    "Goldcrest Avenue",
    "Palm Street",
    "Clearview Road",
    "Silverstone Boulevard",
    "Hawk’s Nest Road",
    "Mimosa Lane",
    "Deerfield Road",
    "Cedarwood Lane",
    "Haven Drive",
    "Ocean Breeze Road",
    "Palm Grove Street",
    "Prairie Trail Road",
    "Golden Fields Drive",
    "Alpine Drive",
    "Windy Oaks Road",
    "Misty Meadows Lane",
    "Violet Hill Road"
]

    startTime = range(5,10)
    endTime = range(15,24)
    
    entrees = [
        "Grilled Ribeye Steak",
        "Chicken Parmesan",
        "Pan-Seared Salmon",
        "Beef Wellington",
        "Lobster Tail",
        "Vegetable Stir-Fry",
        "Eggplant Parmesan",
        "Shrimp Scampi",
        "Lamb Chops",
        "Spaghetti Bolognese",
        "Roast Duck Breast",
        "Chicken Alfredo",
        "BBQ Ribs",
        "Filet Mignon",
        "Fish and Chips",
        "Chicken Marsala",
        "Fettuccine Alfredo",
        "Peking Duck",
        "Moussaka",
        "Vegetarian Lasagna",
        "Pork Schnitzel",
        "Surf and Turf",
        "Grilled Tuna Steak",
        "Pasta Primavera",
        "Beef Tacos",
        "Chicken Quesadillas",
        "Peking Pork",
        "Stuffed Bell Peppers",
        "Baked Ziti",
        "Risotto with Shrimp",
        "Crispy Duck Confit",
        "Seafood Paella",
        "Lobster Mac and Cheese",
        "Veal Piccata",
        "Chicken Cacciatore",
        "Grilled Swordfish",
        "Crispy Fried Catfish",
        "BBQ Pulled Pork Sandwich",
        "Grilled Veggie Skewers",
        "Sushi Rolls (variety)",
        "Crispy Pork Belly",
        "Beef Short Ribs",
        "Chili Con Carne",
        "Tom Yum Soup with Shrimp",
        "Blackened Catfish",
        "Stuffed Chicken Breast",
        "Salmon Teriyaki",
        "Chicken Fried Steak",
        "Pasta Carbonara",
        "Bangers and Mash",
        "Steak Frites",
        "Lobster Roll",
        "Tandoori Chicken",
        "Grilled Shrimp Tacos",
        "Pulled Pork Tacos",
        "Ratatouille",
        "Prime Rib",
        "Salmon en Papillote",
        "Seafood Chowder",
        "Chicken and Waffles",
        "Ceviche",
        "Shakshuka",
        "Fried Calamari",
        "Paella Valenciana",
        "Pasta Puttanesca",
        "Gourmet Burger",
        "Eggplant Rollatini",
        "Salmon Sushi",
        "Chilean Sea Bass",
        "Grilled Portobello Mushroom",
        "Linguine with Clams",
        "Chicken Shawarma",
        "Beef Empanadas",
        "Spicy Tuna Tartare",
        "Gnocchi with Sage Butter",
        "Baked Cod with Lemon and Dill",
        "Shrimp Tacos",
        "Chicken Tikka Masala",
        "Philly Cheesesteak",
        "Crispy Fish Tacos",
        "Grilled Octopus",
        "Lamb Vindaloo",
        "Pork Belly Tacos",
        "Margherita Pizza",
        "Steak Burrito",
        "Lobster Bisque",
        "Vegetarian Burrito",
        "Beef Bulgogi",
        "Sweet and Sour Pork",
        "Salmon Caesar Salad",
        "Chimichurri Steak",
        "Fried Rice with Shrimp",
        "Baked Sweet Potato with Gravy",
        "Shoyu Ramen",
        "Chili Crab",
        "Sushi Sashimi Platter",
        "Vegan Tacos",
        "Steamed Mussels",
        "Lamb Kofta",
        "Grilled Chicken Wings",
        "Chicken Fajitas",
        "Grilled Mahi-Mahi",
        "Tomahawk Steak",
        "Seafood Linguine",
        "Baked Brie with Fruit",
        "Beef Empanada",
        "Shrimp and Grits",
        "Chorizo and Eggs",
        "Vegetarian Sushi Rolls",
        "Chicken Tenders",
        "Grilled Flank Steak",
        "Pan-Seared Scallops",
        "Tuna Poke Bowl",
        "Ginger Soy Glazed Salmon",
        "Chicken Souvlaki",
        "Beef Rendang",
        "Grilled Lamb Kebabs",
        "Seafood Risotto",
        "Chicken Pot Pie",
        "Pork Tenderloin",
        "Barbecue Meatloaf",
        "Bulgur Wheat Salad with Grilled Chicken",
        "Pork Tacos with Pineapple Salsa",
        "Grilled Swordfish Tacos",
        "Beef and Broccoli Stir-Fry",
        "Penne Arrabbiata",
        "Mahi-Mahi Fish Tacos",
        "Lobster and Crab Cakes",
        "Marinated Skirt Steak",
        "Sesame Crusted Tuna",
        "Jambalaya",
        "Zucchini Noodles with Pesto",
        "Fried Green Tomatoes",
        "Chorizo Queso Fundido",
        "Chargrilled Oysters",
        "Beef Kabobs with Rice Pilaf",
        "Crispy Chicken Sandwich",
        "Vegetable Biryani",
        "Beef Wellington Sliders",
        "Baked Macaroni and Cheese",
        "Po' Boy Sandwich",
        "Duck Tacos",
        "Vegan Pad Thai",
        "Fish Tacos with Slaw",
        "Braised Beef Brisket",
        "Crispy Sweet and Sour Chicken",
        "Salmon Burgers",
        "Falafel Plate",
        "Chili Lime Shrimp",
        "Pasta with Roasted Red Pepper Sauce",
        "Pulled BBQ Chicken Sandwich",
        "Grilled Vegetables with Quinoa",
        "Braised Short Ribs",
        "Beef and Spinach Lasagna",
        "Salmon with Herb Butter",
        "Duck Leg Confit",
        "Seared Tuna Steak",
        "Vegetarian Tofu Stir-Fry",
        "Steak and Cheese Sub",
        "Grilled Cheese with Tomato Soup",
        "Lamb Korma",
        "Fried Catfish Po' Boy",
        "Pasta alla Norma",
        "Crispy Fish and Chips",
        "Chicken Parmesan Sub",
        "Garlic Butter Shrimp Pasta",
        "Caribbean Jerk Chicken",
        "Balsamic Glazed Pork Chops",
        "Coconut Shrimp",
        "Tuna Tartare",
        "Smoked Brisket",
        "Crispy Fried Chicken",
        "Fettuccine with Mushroom Cream Sauce"
    ]


    for i in range(numStores):
        start = random.choice(startTime)
        end = random.choice(endTime)
        name = random.choice(restaurantNames)
        ref = {
                "reference": str(random.randint(1,100000)),
                "store": {
                "merchant_supplied_id": str(random.randint(1,100000)),
                "provider_type": name,
                "address" : str(random.randint(1,10000)) + " " + random.choice(streetNames),
                "phone" : "+1" + ''.join([str(random.randint(0,9)) for i in range(10)])
                },
                "open_hours": [
                {
                    "day_index": "MON",
                    "start_time": str(start) + ":00",
                    "end_time": str(end) + ":00"
                },
                {
                    "day_index": "TUE",
                    "start_time": str(start) + ":00",
                    "end_time": str(end) + ":00"
                },
                {
                    "day_index": "WED",
                    "start_time": str(start) + ":00",
                    "end_time": str(end) + ":00"
                },
                {
                    "day_index": "THU",
                    "start_time": str(start) + ":00",
                    "end_time": str(end) + ":00"
                },
                {
                    "day_index": "FRI",
                    "start_time": str(start) + ":00",
                    "end_time": str(end) + ":00"
                }
                ],
                "special_hours": [],
                "menu": {
                "name": "Breakfast",
                "subtitle": "",
                "active": True,
                "categories": [
                    {
                    "name": "Entree",
                    "subtitle": "",
                    "merchant_supplied_id": "Entree",
                    "active": True,
                    "sort_id": 0,
                    "items": [GenItem(entrees) for i in range(random.randint(4,10))]
                    }
                ]
                }
            }
        with open("backend/Stores/" + name + ".json", "w") as outfile:
            json.dump(ref, outfile)
        

def GenItem(entrees):
    a ={
        "name":random.choice(entrees),
        "description": "yummy.",
        "merchant_supplied_id": ''.join([str(random.choice(string.ascii_lowercase+string.digits)) for i in range(12)]),
        "active": True,
        "price": random.randrange(1000,2000)/100,
        "extras": []
        }
    print('yes')
    return a
storeMaker(1)